services:
  web:
    build: .
    container_name: flask_app
    command: gunicorn --bind 0.0.0.0:${APP_PORT} wsgi:app
    ports:
      - ${APP_PORT}
    environment:
      - APP_ENV=monitor-app
      - APP_PORT=${APP_PORT}
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - frontend
      - backend
  webserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - web
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  dbdata:
    driver: local
  nginxdata:
    driver: local