echo "** Creating default DB and users"

mysql -u root -p$MYSQL_ROOT_PASSWORD --execute \
    "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;
     CREATE USER IF NOT EXISTS '$MYSQL_READ_USER'@'%' IDENTIFIED BY '$MYSQL_READ_PASSWORD';
     CREATE USER IF NOT EXISTS '$MYSQL_WRITE_NAME'@'%' IDENTIFIED BY '$MYSQL_WRITE_PASSWORD';
     GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_WRITE_NAME'@'%';
     GRANT SELECT ON $MYSQL_DATABASE.* TO '$MYSQL_READ_USER'@'%';
     FLUSH PRIVILEGES;
     DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"

echo "** Finished creating default DB and users"